#include <stdio.h>

#include "optee_smc.h"
#include "optee_msg.h"
#include "std_smc.h"

int main(int argc, char *argv[])
{
  printf("# ARM STD SMC call identifiers:\n\n");
  printf("ARM_STD_SVC_CALL_COUNT: %lx\n", ARM_STD_SVC_CALL_COUNT);
  printf("ARM_STD_SVC_UID: %lx\n", ARM_STD_SVC_UID);
  printf("ARM_STD_SVC_VERSION: %lx\n", ARM_STD_SVC_VERSION);

  printf("\n# OPTEE SMC call identifiers (OPTEE):\n\n");

  printf("OPTEE_SMC_CALLS_COUNT: %lx\n", OPTEE_SMC_CALLS_COUNT);
  printf("OPTEE_SMC_CALLS_UID: %lx\n", OPTEE_SMC_CALLS_UID);
  printf("OPTEE_SMC_CALLS_REVISION: %lx\n", OPTEE_SMC_CALLS_REVISION);
  printf("OPTEE_SMC_CALL_GET_OS_UUID: %lx\n", OPTEE_SMC_CALL_GET_OS_UUID);
  printf("OPTEE_SMC_CALL_GET_OS_REVISION: %lx\n", OPTEE_SMC_CALL_GET_OS_REVISION);
  printf("OPTEE_SMC_CALL_WITH_ARG: %lx\n", OPTEE_SMC_CALL_WITH_ARG);
  printf("OPTEE_SMC_GET_SHM_CONFIG: %lx\n", OPTEE_SMC_GET_SHM_CONFIG);
  printf("OPTEE_SMC_L2CC_MUTEX: %lx\n", OPTEE_SMC_L2CC_MUTEX);
  printf("OPTEE_SMC_EXCHANGE_CAPABILITIES: %lx\n", OPTEE_SMC_EXCHANGE_CAPABILITIES);
  printf("OPTEE_SMC_DISABLE_SHM_CACHE: %lx\n", OPTEE_SMC_DISABLE_SHM_CACHE);
  printf("OPTEE_SMC_ENABLE_SHM_CACHE: %lx\n", OPTEE_SMC_ENABLE_SHM_CACHE);
  printf("OPTEE_SMC_BOOT_SECONDARY: %lx\n", OPTEE_SMC_BOOT_SECONDARY);
  printf("OPTEE_SMC_VM_CREATED: %lx\n", OPTEE_SMC_VM_CREATED);
  printf("OPTEE_SMC_VM_DESTROYED: %lx\n", OPTEE_SMC_VM_DESTROYED);
  printf("OPTEE_SMC_CALL_RETURN_FROM_RPC: %lx\n", OPTEE_SMC_CALL_RETURN_FROM_RPC);

  printf("\n# OPTEE SMC call identifiers (Linux TEE Driver):\n\n");

  printf("OPTEE_SMC_RETURN_RPC_ALLOC: %lx\n", OPTEE_SMC_RETURN_RPC_ALLOC);
  printf("OPTEE_SMC_RETURN_RPC_FREE: %lx\n", OPTEE_SMC_RETURN_RPC_FREE);
  printf("OPTEE_SMC_RETURN_RPC_FOREIGN_INTR: %lx\n", OPTEE_SMC_RETURN_RPC_FOREIGN_INTR);
  printf("OPTEE_SMC_RETURN_RPC_CMD: %lx\n", OPTEE_SMC_RETURN_RPC_CMD);
  
  printf("\n# bitfield of normal world capabilities OPTEE_SMC_NSEC_CAP_*:\n\n");
  
  printf("OPTEE_SMC_NSEC_CAP_UNIPROCESSOR: %lx\n", OPTEE_SMC_NSEC_CAP_UNIPROCESSOR);
  printf("OPTEE_SMC_SEC_CAP_HAVE_RESERVED_SHM: %lx\n", OPTEE_SMC_SEC_CAP_HAVE_RESERVED_SHM);
  printf("OPTEE_SMC_SEC_CAP_UNREGISTERED_SHM: %lx\n", OPTEE_SMC_SEC_CAP_UNREGISTERED_SHM);
  printf("OPTEE_SMC_SEC_CAP_DYNAMIC_SHM: %lx\n", OPTEE_SMC_SEC_CAP_DYNAMIC_SHM);
  return 0;
}
