#!/bin/bash
sudo bash -c "echo core >/proc/sys/kernel/core_pattern"
sudo bash -c "cd /sys/devices/system/cpu;echo performance | tee cpu*/cpufreq/scaling_governor"

# Disable core dumps
# You can activate core dumps, but this will fill your disk with core dumps in
# optee/arm-trusted-firmware/build/qemu/release
ulimit -c 0
