#!/bin/bash
BASE_PATH=$(dirname "$(readlink -f "$0")")

export IMPORT_LOG_FILE="$BASE_PATH/task/import.log"

# Add syscase path
if ! [ -x "$(command -v import-example)" ]; then
  export PATH="$PATH:$BASE_PATH/syscase/bin"
fi

source "$BASE_PATH/task/config"

export FUZZ_ID=01
export AFL_OUTPUT_PATH=${AFL_OUTPUT_PATH:-"$BASE_PATH/task/outputs"}
COVERAGE_MODE="${COVERAGE_MODE:-0}"
SYSCASE_MODE="${SYSCASE_MODE:-0}"
SYSCASE_JSON_MODE="${SYSCASE_JSON_MODE:-0}"

# Linux Kernel:
# -aflPanicAddr ffff000008174f04 -aflDmesgAddr ffff00000810a7a0 \
# OPTEE Kernel:
# -aflPanicAddr e10ea68 -aflDmesgAddr ffff00000810a7a0 \
# Note: -aflDmesgAddr is not used currently and the value has no effect
# It was used to log dmesg calls to file. The current implementation is not
# supported for aarch64.
"$BASE_PATH/afl/afl"                                    \
  -s "$SYSCASE_MODE"                                    \
  -j "$SYSCASE_JSON_MODE"                               \
  -c "$COVERAGE_MODE"                                   \
  -t 30000                                              \
  -i "$BASE_PATH/task/inputs"                           \
  -o "$BASE_PATH/task/outputs" -QQ -- \
        "$BASE_PATH/qemu-system-aarch64-afl" \
        -aflCoverageAddrStart "$COVERAGE_ADDRESS_START" \
        -aflCoverageAddrEnd "$COVERAGE_ADDRESS_END" \
        -aflPanicAddr "$PANIC_ADDRESS" \
        -aflPanicAddr2 "$PANIC_ADDRESS2" \
        -aflPanicAddr3 "$PANIC_ADDRESS3" \
        -aflPanicAddr4 "$PANIC_ADDRESS4" \
        -aflDmesgAddr "$DMESG_ADDRESS" \
        -aflFile @@
