#!/bin/bash
BASE_PATH=$(dirname "$(readlink -f "$0")")

export IMPORT_LOG_FILE="$BASE_PATH/task/import.log"

# Add syscase path
if ! [ -x "$(command -v import-example)" ]; then
  export PATH="$PATH:$BASE_PATH/syscase/bin"
fi

source "$BASE_PATH/task/config"

export TASK_BACKUP="${TASK_BACKUP:-y}"
export QEMU_TERMINAL="${QEMU_TERMINAL:-screen}"
export AFL_OUTPUT_PATH="${AFL_OUTPUT_PATH:-"$BASE_PATH/task/outputs/m$FUZZ_ID"}"

# Linux Kernel:
# -aflPanicAddr ffff000008174f04 -aflDmesgAddr ffff00000810a7a0 \
# OPTEE Kernel:
# -aflPanicAddr e10ea68 -aflDmesgAddr ffff00000810a7a0 \
# Note: -aflDmesgAddr is not used currently and the value has no effect
# It was used to log dmesg calls to file. The current implementation is not
# supported for aarch64.
"$BASE_PATH/afl/afl-fuzz" -t 30000 -i "$BASE_PATH/task/inputs" -o "$BASE_PATH/task/outputs" -QQS s$FUZZ_ID -- \
        "$BASE_PATH/qemu-system-aarch64-afl" \
        -aflPanicAddr "$PANIC_ADDRESS" -aflDmesgAddr "$DMESG_ADDRESS" \
        -aflFile @@
